/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Clave",                                           "pl": "Hasło",                                           "zh-cn": "密码"},
    "Poll Interval (sec.)": {                        "en": "Poll Interval (sec.)",                            "de": "Abfrageintervall (Sek.)",                         "ru": "Интервал опроса (сек.)",                          "pt": "Intervalo de sondagem (seg.)",                    "nl": "Poll-interval (sec.)",                            "fr": "Intervalle d'interrogation (sec.)",               "it": "Intervallo sondaggio (sec.)",                     "es": "Intervalo de encuesta (seg.)",                    "pl": "Interwał sondowania (sek.)",                      "zh-cn": "轮询间隔（秒）"},
    "Server Address": {                              "en": "Server Address",                                  "de": "Serveradresse",                                   "ru": "Адрес сервера",                                   "pt": "Endereço do servidor",                            "nl": "Server adres",                                    "fr": "Adresse du serveur",                              "it": "Indirizzo del server",                            "es": "Dirección del servidor",                          "pl": "Adres serwera",                                   "zh-cn": "服务器地址"},
    "Server Port": {                                 "en": "Server Port",                                     "de": "Server Port",                                     "ru": "Порт сервера",                                    "pt": "Porta do servidor",                               "nl": "Server poort",                                    "fr": "Port de serveur",                                 "it": "Porta del server",                                "es": "Puerto de servicio",                              "pl": "Port serwera",                                    "zh-cn": "服务器端口"},
    "User": {                                        "en": "User",                                            "de": "Nutzer",                                          "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
};